
/* courseImg, courseImgalt,link, tag,title,lesson,duration,instractorName,instractorphoto,price*/

import { courseweb, instractor1 } from "@/public";

export const courses = [
  {
    courseImg: courseweb,
    courseImgalt: "web",
    link: "/webdesign",
    tag: "Web Development",
    tagbg: "bg-green-600",
    title: "Responsive Web Design",
    lesson: 15,
    duration: "6 Month",
    instractorName: "Mahabub Hossain",
    instractorphoto: instractor1,
    price: 15000,
  },
  {
    courseImg: courseweb,
    courseImgalt: "web",
    link: "/office",
    tag: "Office",
    tagbg: "bg-red-600",
    title: "Microsoft Office Application",
    lesson: 10,
    duration: "3 Month",
    instractorName: "Moniruzzaman",
    instractorphoto: instractor1,
    price: 5000,
  },

  {
    courseImg: courseweb,
    courseImgalt: "web",
    link: "/office",
    tag: "Office",
    tagbg: "bg-red-600",
    title: "Graphics Design",
    lesson: 10,
    duration: "3 Month",
    instractorName: "Moniruzzaman",
    instractorphoto: instractor1,
    price: 5000,
  },
  {
    courseImg: courseweb,
    courseImgalt: "web",
    link: "/office",
    tag: "Office",
    tagbg: "bg-red-600",
    title: "English Language",
    lesson: 10,
    duration: "3 Month",
    instractorName: "Moniruzzaman",
    instractorphoto: instractor1,
    price: 5000,
  },
  {
    courseImg: courseweb,
    courseImgalt: "web",
    link: "/office",
    tag: "Office",
    tagbg: "bg-red-600",
    title: "Video Editing",
    lesson: 10,
    duration: "3 Month",
    instractorName: "Moniruzzaman",
    instractorphoto: instractor1,
    price: 5000,
  },
  {
    courseImg: courseweb,
    courseImgalt: "web",
    link: "/office",
    tag: "Office",
    tagbg: "bg-red-600",
    title: "Auto CAD 2D/3D",
    lesson: 10,
    duration: "3 Month",
    instractorName: "Moniruzzaman",
    instractorphoto: instractor1,
    price: 5000,
  },
];
