/* courseImg, courseImgalt,link, tag,title,lesson,duration,instractorName,instractorphoto,price*/

import { autocad, computer, courseweb, instractor1 } from "@/public";

export const courses = [
  {
    courseImg: courseweb,
    courseImgalt: "web",
    link: "/webdesign",
    tag: "Web Development",
    tagbg: "bg-green-600",
    title: "Responsive Web Design",
    lesson: 15,
    duration: "3",
    instractorName: "Moniruzzaman",
    instractorphoto: instractor1,
    price: 12000,
  },
  {
    courseImg: courseweb,
    courseImgalt: "web",
    link: "/webdevlopment",
    tag: "Web Development",
    tagbg: "bg-green-600",
    title: "Advanced Web Development",
    lesson: 15,
    duration: "6",
    instractorName: "Engr Mahabub Hossain",
    instractorphoto: instractor1,
    price: 25000,
  },

  {
    courseImg: autocad,
    courseImgalt: "web",
    link: "/office",
    tag: "Autocad",
    tagbg: "bg-teal-600",
    title: "Auto CAD 2D/3D",
    lesson: 10,
    duration: "3",
    instractorName: "Moniruzzaman",
    instractorphoto: instractor1,
    price: 6000,
  },

  {
    courseImg: computer,
    courseImgalt: "web",
    link: "/office",
    tag: "Hardware",
    tagbg: "bg-teal-600",
    title: "Sketch Up 3D Design",
    lesson: 10,
    duration: "2",
    instractorName: "Moniruzzaman",
    instractorphoto: instractor1,
    price: 5000,
  },

  {
    courseImg: autocad,
    courseImgalt: "web",
    link: "/office",
    tag: "Autocad",
    tagbg: "bg-teal-600",
    title: "Studio 3D Max",
    lesson: 10,
    duration: "3",
    instractorName: "Moniruzzaman",
    instractorphoto: instractor1,
    price: 14000,
  },
  {
    courseImg: courseweb,
    courseImgalt: "web",
    link: "/office",
    tag: "Office",
    tagbg: "bg-red-600",
    title: "Computer Office Application",
    lesson: 10,
    duration: "3",
    instractorName: "Moniruzzaman",
    instractorphoto: instractor1,
    price: 4500,
  },
  {
    courseImg: courseweb,
    courseImgalt: "web",
    link: "/office",
    tag: "Office",
    tagbg: "bg-red-600",
    title: "Advanced Office Application",
    lesson: 10,
    duration: "6",
    instractorName: "Moniruzzaman",
    instractorphoto: instractor1,
    price: 6000,
  },
  {
    courseImg: courseweb,
    courseImgalt: "web",
    link: "/office",
    tag: "Graphics Design",
    tagbg: "bg-purple-600",
    title: "Advanced Graphics Design",
    lesson: 10,
    duration: "3",
    instractorName: "Moniruzzaman",
    instractorphoto: instractor1,
    price: 7000,
  },
  {
    courseImg: courseweb,
    courseImgalt: "web",
    link: "/office",
    tag: "Language",
    tagbg: "bg-pink-600",
    title: "English Language Courses",
    lesson: 10,
    duration: "3",
    instractorName: "Moniruzzaman",
    instractorphoto: instractor1,
    price: 5000,
  },
  {
    courseImg: courseweb,
    courseImgalt: "web",
    link: "/office",
    tag: "Language",
    tagbg: "bg-pink-600",
    title: "Japani Language",
    lesson: 10,
    duration: "4",
    instractorName: "Moniruzzaman",
    instractorphoto: instractor1,
    price: 25000,
  },
  {
    courseImg: courseweb,
    courseImgalt: "web",
    link: "/office",
    tag: "Editing",
    tagbg: "bg-red-600",
    title: "Video Editing",
    lesson: 10,
    duration: "2",
    instractorName: "Moniruzzaman",
    instractorphoto: instractor1,
    price: 5000,
  },

  {
    courseImg: computer,
    courseImgalt: "web",
    link: "/office",
    tag: "Hardware",
    tagbg: "bg-teal-600",
    title: "Computer Hardware",
    lesson: 10,
    duration: "3",
    instractorName: "Moniruzzaman",
    instractorphoto: instractor1,
    price: 7000,
  },
];
