/* courseImg, courseImgalt,link, tag,title,lesson,duration,instractorName,instractorphoto,price*/

import { advancedweb, autocad, autocadprogram, computer, computerhardware, courseweb, digitalmarketing, freelancing, graphics, graphicsdesign, informationatechnology, instractor1, instractor2, instractor3, instractor4, instractor5, instractor6, instractor7, japanilanguage, max, office, officeapplication, responsive, sketch, spokenenglish, videoediting } from "@/public";
import { instractor } from "./instractor";

export const courses = [
  {
    courseImg: responsive,
    courseImgalt: "responsive",
    link: "webdesign",
    tag: "Web Development",
    tagbg: "bg-fuchsia-800",
    title: "Responsive Web Design",
    lesson: 15,
    duration: "3",
    instractorName: "Moniruzzaman",
    instractorphoto: instractor1,
    price: 12000,
  },
  {
    courseImg: advancedweb,
    courseImgalt: "advancedweb",
    link: "advancedweb",
    tag: "Web Development",
    tagbg: "bg-fuchsia-800",
    title: "Web Developmet ",
    lesson: 30,
    duration: "6",
    instractorName: instractor[2].name,
    instractorphoto: instractor6,
    price: 25000,
  },

  {
    courseImg: autocadprogram,
    courseImgalt: "autocadprogram",
    link: "autocad",
    tag: "Autocad",
    tagbg: "bg-teal-600",
    title: "Auto CAD 2D/3D",
    lesson: 10,
    duration: "3",
    instractorName: instractor[0].name,
    instractorphoto: instractor1,
    price: 6000,
  },

  {
    courseImg: sketch,
    courseImgalt: "sketchup",
    link: "sketchup",
    tag: "Sketchup",
    tagbg: "bg-rose-600",
    title: "Sketch Up 3D Design",
    lesson: 10,
    duration: "2",
    instractorName: instractor[5].name,
    instractorphoto: instractor5,
    price: 5000,
  },

  {
    courseImg: max,
    courseImgalt: "max",
    link: "3dmax",
    tag: "3D Max",
    tagbg: "bg-teal-600",
    title: "Studio 3D Max",
    lesson: 10,
    duration: "3",
    instractorName: instractor[5].name,
    instractorphoto: instractor5,
    price: 14000,
  },
  {
    courseImg: officeapplication,
    courseImgalt: "officeapplication",
    link: "office",
    tag: "Office",
    tagbg: "bg-purple-800",
    title: "Computer Office Application",
    lesson: 10,
    duration: "3",
    instractorName: instractor[3].name,
    instractorphoto: instractor3,
    price: 4500,
  },
  {
    courseImg: officeapplication,
    courseImgalt: "office",
    link: "advancedoffice",
    tag: "Office",
    tagbg: "bg-red-600",
    title: "Advanced Office Application",
    lesson: 10,
    duration: "6",
    instractorName: instractor[3].name,
    instractorphoto: instractor3,
    price: 6000,
  },
  {
    courseImg: graphicsdesign,
    courseImgalt: "graphicsdesign",
    link: "graphics",
    tag: "Graphics Design",
    tagbg: "bg-purple-600",
    title: "Advanced Graphics Design",
    lesson: 10,
    duration: "3",
    instractorName: instractor[4].name,
    instractorphoto: instractor4,
    price: 7000,
  },
  {
    courseImg: spokenenglish,
    courseImgalt: "spokenenglish",
    link: "english",
    tag: "Language",
    tagbg: "bg-pink-600",
    title: "English Language Courses",
    lesson: 10,
    duration: "3",
    instractorName: instractor[6].name,
    instractorphoto: instractor7,
    price: 5000,
  },
  {
    courseImg: japanilanguage,
    courseImgalt: "japani",
    link: "japani",
    tag: "Language",
    tagbg: "bg-pink-800",
    title: "Japani Language",
    lesson: 10,
    duration: "4",
    instractorName: instractor[6].name,
    instractorphoto: instractor7,
    price: 25000,
  },
  {
    courseImg: videoediting,
    courseImgalt: "videoediting",
    link: "videoediting",
    tag: "Video Editing",
    tagbg: "bg-red-600",
    title: "Video Editing",
    lesson: 10,
    duration: "2",
    instractorName: "Moniruzzaman",
    instractorphoto: instractor1,
    price: 5000,
  },

  {
    courseImg: computerhardware,
    courseImgalt: "web",
    link: "hardware",
    tag: "Hardware",
    tagbg: "bg-teal-800",
    title: "Computer Hardware",
    lesson: 10,
    duration: "3",
    instractorName: "Moniruzzaman",
    instractorphoto: instractor1,
    price: 7000,
  },
  {
    courseImg: informationatechnology,
    courseImgalt: "ict",
    link: "ict",
    tag: "Hardware",
    tagbg: "bg-teal-800",
    title: "ICT HSC/SSC",
    lesson: 10,
    duration: "3",
    instractorName: instractor[1].name,
    instractorphoto: instractor2,
    price: 7000,
  },
  {
    courseImg: digitalmarketing,
    courseImgalt: "digitalmarketing",
    link: "digitalmarketing",
    tag: "Digital Marketing",
    tagbg: "bg-lime-800",
    title: "Digital Marketing",
    lesson: 10,
    duration: "3",
    instractorName: instractor[1].name,
    instractorphoto: instractor2,
    price: 7000,
  },
  {
    courseImg: freelancing,
    courseImgalt: "freelancing",
    link: "freelancing",
    tag: "Freelancing",
    tagbg: "bg-orange-700",
    title: "Freelancing Course",
    lesson: 10,
    duration: "3",
    instractorName: "Moniruzzaman",
    instractorphoto: instractor1,
    price: 6000,
  },
];
